stages:
  - check
  - release

variables:
  GOPATH: $CI_PROJECT_DIR/.go

cache:
  paths:
    - .go/pkg/mod/

.go-template: &go-template
  image: golang:1.24
  before_script:
    - mkdir -p $GOPATH

check:
  <<: *go-template
  stage: check
  script:
    - test -z "$(gofmt -l *.go internal/)" || (echo "Files need formatting:" && gofmt -l *.go internal/ && exit 1)
    - go vet ./...
    - go test -race -cover ./...

release:
  stage: release
  image: goreleaser/goreleaser:latest
  before_script: []
  cache: []
  variables:
    GIT_DEPTH: 0
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  script:
    - goreleaser release --clean
